routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource ('artist', 'ArtistController');

Route::resource('movie', 'MovieController');

Route::resource('cinema', 'CinemaController');

Route::resource('room', 'RoomController');

resources/views/movies/create.blade.php
@extends('layouts.app')
@section('title', 'Add new cinema')
@section('content')

<main>
    <div class="container">
        <h1 class="display-6" style="text-align: center;  margin-top: 50px;">Add new movie</h1>

        <form method="POST" action="{{ route('movie.store') }}" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" id="title" value="" class="form-control form-control-sm" required />
            </div>

            <div class="form-group">
                <label for="year">Year</label>
                <input type="number" name="year" id="year" value="" class="form-control form-control-sm" required />
            </div>

            <div class="form-group">
                <label for="artist_id">Pour quel cinema ?</label>
                <select class="custom-select" name="artist_id" required>
                    @foreach($artists as $artist)
                        <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="poster">Poster movie</label>
                <input class="form-control form-control-file form-control-sm" type="file" name="poster" id="poster">
            </div>

            <button type="submit" class="btn btn-dark" style="display: block; margin: 0 auto;">Create</button>
        </form>
    </div>
</main>
@endsection

resources/views/movies/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit a movie')
@section('content')

<main>
    <div class="container">
        <h1 class="display-6" style="text-align: center; margin-top: 50px;">Edit a movie</h1>

        <form method="POST" action="{{ route('movie.update', $movie->id) }}">

            {{ csrf_field() }}
            {{method_field('PUT')}}
            
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" id="title" class="form-control form-control-sm" value="{{ $movie->title }}" required />
            </div>

            <div class="form-group">
                <label for="year">Year</label>
                <input type="number" name="year" id="year" class="form-control form-control-sm" value="{{ $movie->year }}" required />
            </div>
            <div class="form-group">
                <select class="custom-select" name="artist_id" required>
                    @foreach($artists as $artist)
                        <option value="{{ $artist->id }}">{{ $artist->name }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-dark" style="display: block; margin: 0 auto;">Modify</button>
        </form>
    </div>
</main>
@endsection

resources/views/movies/index.blade.php
@extends('layouts.app')
@section('title', 'All movies')
@section('content')
<main>
    <div class="container">

        <h1 class="display-6" style="text-align: center; margin: 50px 0;">All movies</h1>

        @if (session('ok'))
        <div class="container">
            <div class="alert alert-dismissible alert-success fade show" role="alert">
                {{ session('ok') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif

        <table class="table table-hover table-striped table-sm">
            <thead>
                <tr>
                    <th scope="row">{{ __('Title') }}</th>
                    <th>{{ __('Year') }}</th>
                    <th>{{ __('Director') }}</th>
                    <th>{{ __('Poster') }}</th>
                    <th>{{ __('Actions') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($movies as $movie)
                <tr>
                    <td><a href="/movie/{{$movie->id}}">{{ $movie->title }}</td>
                    <td>{{ $movie->year }}</td>
                    <td>{{ $movie->director->firstname }} {{ $movie->director->name }}</td>
                    <td><img class="img-thumbnail" style="width: 180px; height: 240px;" src="/uploads/posters/poster_{{ $movie->id}}.jpeg"></td>

                    <td class="table-action">
                        <a type="button" href="{{ route('movie.edit', $movie->id) }}" class="btn btn-sm"
                            data-toggle="tooltip" title="@lang('Edit movie') {{ $movie->title }}">
                            <i class="fas fa-edit fa-lg"></i>
                        </a>
                        <a type="button" href="{{ route('movie.destroy', $movie->id) }}"
                            class="btn btn-danger btn-sm btn-delete" data-toggle="tooltip"
                            title="@lang('Delete artist') {{$movie->title}}">
                            <i class="fas fa-trash fa-lg"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="center-element" style="display: flex; justify-content: center;">
            {{ $movies->appends(request()->except('page'))->links() }}
        </div>
    </div>
</main>
<script>
    $.ajaxSetup({
            headers: {'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')}
        })

        $(document).on('click', '.btn-delete', function(){

            let button = $(this);

            $.ajax({
                url: $(this).attr('href'),
                type: 'DELETE'
            }).done(function(){
                button.closest('tr').remove();
            });
            return false;
        });
</script>
@endsection

resources/views/movies/show.blade.php
@extends('layouts.app')
@section('title', 'Specific movie')
@section('content')

<main>
    <div class="container">

        <h1 class="display-6" style="text-align: center; margin: 50px 0;">{{ $movie->title }}</h1>

        <div class="card" style="width: 18rem; margin: 0 auto;">
            <img src="/uploads/posters/poster_{{ $movie->id}}.jpeg" class="card-img-top" alt="{{ $movie->title}}">
            <div class="card-body">
                <h5 class="card-title">{{ $movie->title }}</h5>
                <p class="card-text">
                    {{ $movie->year }} 
                    <br>
                    Directed by: {{ $movie->director->firstname }} {{ $movie->director->name }}
                </p>
            </div>
        </div>
    </div>
    </div>
</main>
@endsection