routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource ('artist', 'ArtistController');

Route::resource('movie', 'MovieController');

Route::resource('cinema', 'CinemaController');

Route::resource('room', 'RoomController');

app/Models/Room.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Room extends Model
{
    protected $fillable = [
        'name', 'capacity', 'cinema_id',
    ];

    // Liaison one-to-many avec la table cinema
    public function is_managed_by(){
		return $this->belongsTo(Cinema::class, 'cinema_id');
    }
    
    // Liaison many-to-many avec la table movie 
    // Le pivot permet d'ajouter de nouveaux attributs autres que les clés PK et FK
 	public function projects(){
		return $this->belongsToMany('App\Models\Movie')->withPivot('date_hour_start');
	}
}

app/Http/Controllers/RoomController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\Room;
use \App\Models\Cinema;

class RoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('room.index', ['rooms' => Room::paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('room.create', ['cinemas' => Cinema::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\RoomRequest $request)
    {
        Room::create($request->all());
        return redirect()->route('movie.create')
                        ->with('ok', __('Room has been saved'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $room = Room::find($id);
        return view('room.show')->with('room', $room);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Room $room)
    {
        return view('room.edit', ['room' => $room], ['cinemas' => Cinema::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Room $room)
    {
        $room->update( $request->all());

        return redirect()->route('room.index')
                        ->with('ok', __('Room has been updated') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Room $room)
    {
        $room->delete();
        return response()->json(); 
    }

    public function __construct(){
        $this->middleware('ajax')->only('destroy');
    }
}

resources/views/room/create.blade.php
@extends('layouts.app')
@section('title', 'Add new room')
@section('content')

<main>
    <div class="container">
        <h1 class="display-6" style="text-align: center;  margin-top: 50px;">Add new room</h1>

        <form method="POST" action="{{ route('room.store') }}">
            {{ csrf_field() }}

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" value="" class="form-control form-control-sm" placeholder="Ex: Salle 1" required />
            </div>

            <div class="form-group">
                <label for="capacity">Capacity</label>
                <input type="number" name="capacity" id="capacity" value="" class="form-control form-control-sm" required />
            </div>

            <div class="form-group">
                <label for="cinema_id">Pour quel cinema ?</label>
                <select class="custom-select" name="cinema_id" required>
                    @foreach($cinemas as $cinema)
                        <option value="{{ $cinema->id }}">{{ $cinema->name }}</option>
                    @endforeach
                </select>
            </div>

            <button type="submit" class="btn btn-dark" style="display: block; margin: 0 auto;">Create</button>
        </form>
    </div>
</main>
@endsection

resources/views/room/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit a room')
@section('content')

<main>
    <div class="container">
        <h1 class="display-6" style="text-align: center; margin-top: 50px;">Edit a room</h1>

        <form method="POST" action="{{ route('room.update', $room->id) }}">

            {{ csrf_field() }}
            {{method_field('PUT')}}
            
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" value="{{ $room->name }}" class="form-control form-control-sm" placeholder="Ex: Salle 1" required />
            </div>

            <div class="form-group">
                <label for="capacity">Capacity</label>
                <input type="number" name="capacity" id="capacity" value="{{ $room->capacity }}" class="form-control form-control-sm" required />
            </div>

            <div class="form-group">
                <label for="cinema_id">Pour quel cinema ?</label>
                <select class="custom-select" name="cinema_id" required>
                    @foreach($cinemas as $cinema)
                        <option value="{{ $cinema->id }}">{{ $cinema->name }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-dark" style="display: block; margin: 0 auto;">Modify</button>
        </form>
    </div>
</main>
@endsection

resources/views/room/index.blade.php
@extends('layouts.app')
@section('title', 'All rooms')
@section('content')
<main>
    <div class="container">

        <h1 class="display-6" style="text-align: center; margin: 50px 0;">All rooms</h1>

        @if (session('ok'))
        <div class="container">
            <div class="alert alert-dismissible alert-success fade show" role="alert">
                {{ session('ok') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif

        <table class="table table-hover table-striped table-sm">
            <thead>
                <tr>
                    <th scope="row">{{ __('Name') }}</th>
                    <th>{{ __('Capacity') }}</th>
                    <th>{{ __('Cinema') }}</th>
                    <th>{{ __('Actions') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($rooms as $room)
                <tr>
                    <td><a href="/room/{{$room->id}}">{{ $room->name }}</a></td>
                    <td>{{ $room->capacity }}</td>
                    <td>{{ $room->id_cinema }} {{ $room->is_managed_by->name }}</td>

                    <td class="table-action">
                        <a type="button" href="{{ route('room.edit', $room->id) }}" class="btn btn-sm"
                            data-toggle="tooltip" title="@lang('Edit room') {{ $room->name }}">
                            <i class="fas fa-edit fa-lg"></i>
                        </a>
                        <a type="button" href="{{ route('room.destroy', $room->id) }}"
                            class="btn btn-danger btn-sm btn-delete" data-toggle="tooltip"
                            title="@lang('Delete room') {{$room->name}}">
                            <i class="fas fa-trash fa-lg"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="center-element" style="display: flex; justify-content: center;">
            {{ $rooms->appends(request()->except('page'))->links() }}
        </div>
    </div>
</main>
<script>
    $.ajaxSetup({
            headers: {'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')}
        })

        $(document).on('click', '.btn-delete', function(){

            let button = $(this);

            $.ajax({
                url: $(this).attr('href'),
                type: 'DELETE'
            }).done(function(){
                button.closest('tr').remove();
            });
            return false;
        });
</script>
@endsection

resources/views/room/show.blade.php
@extends('layouts.app')
@section('title', 'Specific room')
@section('content')

<main>
    <div class="container">

        <h1 class="display-6" style="text-align: center; margin: 50px 0;">{{$room->name}}</h1>

        <ul class="list-group">
            <li class="list-group-item" style="text-align:center;">{{$room->id}}</li>
            <li class="list-group-item" style="text-align:center;">{{$room->name}}</li>
            <li class="list-group-item" style="text-align:center;">{{$room->capacity}}</li>
            <li class="list-group-item" style="text-align:center;">{{$room->cinema_id}}</li>
        </ul>
    </div>
</main>
@endsection