routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource ('artist', 'ArtistController');

Route::resource('movie', 'MovieController');

Route::resource('cinema', 'CinemaController');

Route::resource('room', 'RoomController');

app/Models/Cinema.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Cinema extends Model
{
    protected $fillable = [
        'name', 'street', 'postcode', 'city', 'country'
    ];

   // Liaison one_to_many avec la table room (Un cinéma gère plusieurs salles)
    public function manages(){
		return $this->hasMany('App\Models\Room');
	}
}

app/Http/Controllers/CinemaController.php
<?php

namespace App\Http\Controllers;

use \App\Models\Cinema;
use Illuminate\Http\Request;

class CinemaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cinemas.index', ['cinemas' => Cinema::paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cinemas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\CinemaRequest $request)
    {
        Cinema::create($request->all());
        return redirect()->route('cinema.create')
                        ->with('ok',__ ('Cinema has been saved'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cinema = Cinema::find($id);
        return view('cinemas.show')->with('cinema', $cinema);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Cinema $cinema)
    {
        return view('cinemas.edit', ['cinema' => $cinema]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cinema $cinema)
    {
        $cinema->update( $request->all() );

        return redirect()->route('cinema.index')
                        ->with('ok', __('Cinema has been updated') );
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cinema $cinema)
    {
        $cinema->delete();
        return response()->json();
    }

    public function __construct(){
        $this->middleware('ajax')->only('destroy');
    }
}

resources/views/cinemas/create.blade.php
@extends('layouts.app')
@section('title', 'Add new cinema')
@section('content')

<main>
    <div class="container">

        <h1 class="display-6" style="text-align: center; margin-top: 50px;">Add new cinema</h1>
        
        <form method="POST" action="{{ route('cinema.store') }}">
            {{ csrf_field() }}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control form-control-sm" value="" required />
            </div>

            <div class="form-group">
                <label for="street">Street</label>
                <input type="text" name="stret" id="street" value="" class="form-control form-control-sm" required />
            </div>

            <div class="form-group">
                <label for="postcode">Postcode</label>
                <input type="number" name="postcode" id="postcode" value="" class="form-control form-control-sm"
                    required />
            </div>

            <div class="form-group">
                <label for="city">City</label>
                <input type="text" name="city" id="city" value="" class="form-control form-control-sm" required />
            </div>

            <div class="form-group">
                <label for="country">Country</label>
                <input type="text" name="country" id="country" value="" class="form-control form-control-sm" required />
            </div>
            <button type="submit" class="btn btn-dark" style="display: block; margin: 0 auto;">Create</button>
        </form>
    </div>
</main>
@endsection

resources/views/cinemas/edit.blade.php
@extends('layouts.app')
@section('title', 'Edit cinema')
@section('content')

<main>
    <div class="container">
        <h1 class="display-1" style="text-align: center; margin-top: 50px;">Edit a cinema</h1>

        <form method="POST" action="{{ route('cinema.update', $cinema->id) }}">

            {{ csrf_field() }}
            {{method_field('PUT')}}

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" name="name" id="name" class="form-control form-control-sm"
                    value="{{ $cinema->name }}" required />
            </div>

            <div class="form-group">
                <label for="street">Street</label>
                <input type="text" name="street" id="street" class="form-control form-control-sm"
                    value="{{ $cinema->street }}" required />
            </div>
            <div class="form-group">
                <label for="postcode">Postcode</label>
                <input type="number" name="postcode" id="postcode" class="form-control form-control-sm"
                    value="{{ $cinema->postcode }}" required />
            </div>
            <div class="form-group">
                <label for="city">City</label>
                <input type="text" name="city" id="city" class="form-control form-control-sm"
                    value="{{ $cinema->city }}" required />
            </div>
            <div class="form-group">
                <label for="country">Country</label>
                <input type="text" name="country" id="country" class="form-control form-control-sm"
                    value="{{ $cinema->country }}" required />
            </div>

            <button type="submit" class="btn btn-dark" style="display: block; margin: 0 auto;">Modify</button>
        </form>
    </div>
</main>
@endsection

resources/views/cinemas/index.blade.php
@extends('layouts.app')
@section('title', 'All cinemas')
@section('content')

<main>
    <div class="container">

        <h1 class="display-6" style="text-align: center;  margin: 50px 0;">All cinemas</h1>

        @if (session('ok'))
        <div class="container">
            <div class="alert alert-dismissible alert-success fade show" role="alert">
                {{ session('ok') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        @endif

        <table class="table table-hover table-striped table-sm">
            <thead>
                <tr>
                    <th scope="row">{{ __('Name') }}</th>
                    <th>{{ __('Street') }}</th>
                    <th>{{ __('Postcode') }}</th>
                    <th>{{ __('City') }}</th>
                    <th>{{ __('Country') }}</th>
                    <th>{{ __('Actions') }}</th>
                </tr>
            </thead>
            <tbody>
                @foreach($cinemas as $cinema)
                <tr>
                    <td><a href="/cinema/{{$cinema->id}}">{{ $cinema->name }}</td>
                    <td>{{ $cinema->street }}</td>
                    <td>{{ $cinema->postcode }}</td>
                    <td>{{ $cinema->city }}</td>
                    <td>{{ $cinema->country }}</td>

                    <td class="table-action">
                        <a type="button" href="{{ route('cinema.edit', $cinema->id) }}" class="btn btn-sm"
                            data-toggle="tooltip" title="@lang('Edit cinema') {{ $cinema->name }}">
                            <i class="fas fa-edit fa-lg"></i>
                        </a>
                        <a type="button" href="{{ route('cinema.destroy', $cinema->id) }}"
                            class="btn btn-danger btn-sm btn-delete" data-toggle="tooltip"
                            title="@lang('Delete cinema') {{$cinema->name}}">
                            <i class="fas fa-trash fa-lg"></i>
                        </a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <div class="center-element" style="display: flex; justify-content: center;">
            {{ $cinemas->appends(request()->except('page'))->links() }}
        </div>
    </div>
</main>


<script>
    $.ajaxSetup({
            headers: {'X-CSRF-TOKEN' : $('meta[name="csrf-token"]').attr('content')}
        })

        $(document).on('click', '.btn-delete', function(){

            let button = $(this);

            $.ajax({
                url: $(this).attr('href'),
                type: 'DELETE'
            }).done(function(){
                button.closest('tr').remove();
            });
            return false;
        });
</script>
@endsection

resources/views/cinemas/show.blade.php
@extends('layouts.app')
@section('title', 'Specific cinema')
@section('content')

<main>
    <div class="container">

        <h1 class="display-6" style="text-align: center; margin: 50px 0;">{{ $cinema->name }}</h1>

        <ul class="list-group">
            <li class="list-group-item" style="text-align:center;">{{ $cinema->id }}</li>
            <li class="list-group-item" style="text-align:center;">{{ $cinema->name }}</li>
            <li class="list-group-item" style="text-align:center;">{{ $cinema->street }}</li>
            <li class="list-group-item" style="text-align:center;">{{ $cinema->postcode }}</li>
            <li class="list-group-item" style="text-align:center;">{{ $cinema->country }}</li>
            <li class="list-group-item" style="text-align:center;">{{ $cinema->city }}</li>
        </ul>
    </div>
</main>
@endsection